"""Generate docs/CODEBASE_MAP.md from every file's 5W+I header.
5W+I: WHO Claude for Monty. WHAT walks the repo, extracts each module's
WHO/WHAT/WHY/INTERCONNECTED header, and writes a single navigation index so a
future LLM can locate any component and its failure modes instantly (Monty:
'the llm will know exactly what the issue is'). WHEN 2026-07-19. WHERE run
after structural changes. WHY the doctrine's LLM-readability requirement.
INTERCONNECTED: every *.py 5W header; docs/CODEBASE_MAP.md (out).
"""
import os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def header(path):
    try:
        txt = open(path, encoding="utf-8").read()[:2500]
    except Exception:
        return {}
    out = {}
    for key in ("WHO", "WHAT", "WHY", "WHERE", "INTERCONNECTED WITH", "INTERCONNECTED"):
        m = re.search(rf"{key}:\s*(.+?)(?:\n[A-Z]{{2,}}[: ]|\n-{{5,}}|\n\"\"\"|\n#|$)",
                      txt, re.S)
        if m and key.split()[0] not in out:
            out[key.split()[0]] = " ".join(m.group(1).split())[:300]
    return out

SKIP = ("__pycache__", ".git", "artifacts", "logs", ".venv")
rows = []
for dirpath, dirs, files in os.walk(ROOT):
    dirs[:] = [d for d in dirs if d not in SKIP]
    for f in sorted(files):
        if not f.endswith(".py") or f == "__init__.py":
            continue
        rel = os.path.relpath(os.path.join(dirpath, f), ROOT)
        h = header(os.path.join(dirpath, f))
        if h.get("WHAT"):
            rows.append((rel, h))

lines = ["# CODEBASE MAP — every file, what it does, what it touches",
         "<!-- AUTO-GENERATED by scripts/build_codebase_map.py from each file's",
         "5W+I header. Regenerate after structural changes. This is the LLM's",
         "index: to debug an issue, find the symptom's area below, open the file,",
         "read its 5W+I header for WHO/WHAT/WHY/INTERCONNECTED. -->",
         "",
         f"{len(rows)} documented modules.", ""]
for rel, h in rows:
    lines.append(f"### `{rel}`")
    lines.append(f"- **What:** {h.get('WHAT','')}")
    if h.get("WHY"): lines.append(f"- **Why:** {h.get('WHY','')}")
    if h.get("INTERCONNECTED"): lines.append(f"- **Touches:** {h.get('INTERCONNECTED','')}")
    lines.append("")
open(os.path.join(ROOT, "docs", "CODEBASE_MAP.md"), "w").write("\n".join(lines))
print(f"CODEBASE_MAP.md written — {len(rows)} modules indexed")
